#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_Parcial_Grupo12
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BaseCargaAlumnos")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTablaCargaAlumno(TablaCargaAlumno instance);
    partial void UpdateTablaCargaAlumno(TablaCargaAlumno instance);
    partial void DeleteTablaCargaAlumno(TablaCargaAlumno instance);
    partial void InsertComentarios(Comentarios instance);
    partial void UpdateComentarios(Comentarios instance);
    partial void DeleteComentarios(Comentarios instance);
    #endregion
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TablaCargaAlumno> TablaCargaAlumno
		{
			get
			{
				return this.GetTable<TablaCargaAlumno>();
			}
		}
		
		public System.Data.Linq.Table<Comentarios> Comentarios
		{
			get
			{
				return this.GetTable<Comentarios>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TablaCargaAlumno")]
	public partial class TablaCargaAlumno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Apellido;
		
		private string _Nombre;
		
		private int _Dni;
		
		private string _Email;
		
		private string _Turno;
		
		private EntityRef<Comentarios> _Comentarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDniChanging(int value);
    partial void OnDniChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTurnoChanging(string value);
    partial void OnTurnoChanged();
    #endregion
		
		public TablaCargaAlumno()
		{
			this._Comentarios = default(EntityRef<Comentarios>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dni", DbType="Int NOT NULL")]
		public int Dni
		{
			get
			{
				return this._Dni;
			}
			set
			{
				if ((this._Dni != value))
				{
					this.OnDniChanging(value);
					this.SendPropertyChanging();
					this._Dni = value;
					this.SendPropertyChanged("Dni");
					this.OnDniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Turno", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Turno
		{
			get
			{
				return this._Turno;
			}
			set
			{
				if ((this._Turno != value))
				{
					this.OnTurnoChanging(value);
					this.SendPropertyChanging();
					this._Turno = value;
					this.SendPropertyChanged("Turno");
					this.OnTurnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TablaCargaAlumno_Comentarios", Storage="_Comentarios", ThisKey="ID", OtherKey="idComentario", IsUnique=true, IsForeignKey=false)]
		public Comentarios Comentarios
		{
			get
			{
				return this._Comentarios.Entity;
			}
			set
			{
				Comentarios previousValue = this._Comentarios.Entity;
				if (((previousValue != value) 
							|| (this._Comentarios.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Comentarios.Entity = null;
						previousValue.TablaCargaAlumno = null;
					}
					this._Comentarios.Entity = value;
					if ((value != null))
					{
						value.TablaCargaAlumno = this;
					}
					this.SendPropertyChanged("Comentarios");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Comentarios")]
	public partial class Comentarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idComentario;
		
		private int _DNI;
		
		private string _Apellido;
		
		private string _ComentarioTexto;
		
		private EntityRef<TablaCargaAlumno> _TablaCargaAlumno;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidComentarioChanging(int value);
    partial void OnidComentarioChanged();
    partial void OnDNIChanging(int value);
    partial void OnDNIChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnComentarioTextoChanging(string value);
    partial void OnComentarioTextoChanged();
    #endregion
		
		public Comentarios()
		{
			this._TablaCargaAlumno = default(EntityRef<TablaCargaAlumno>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idComentario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idComentario
		{
			get
			{
				return this._idComentario;
			}
			set
			{
				if ((this._idComentario != value))
				{
					if (this._TablaCargaAlumno.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidComentarioChanging(value);
					this.SendPropertyChanging();
					this._idComentario = value;
					this.SendPropertyChanged("idComentario");
					this.OnidComentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="Int NOT NULL")]
		public int DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this.OnDNIChanging(value);
					this.SendPropertyChanging();
					this._DNI = value;
					this.SendPropertyChanged("DNI");
					this.OnDNIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComentarioTexto", DbType="VarChar(1500) NOT NULL", CanBeNull=false)]
		public string ComentarioTexto
		{
			get
			{
				return this._ComentarioTexto;
			}
			set
			{
				if ((this._ComentarioTexto != value))
				{
					this.OnComentarioTextoChanging(value);
					this.SendPropertyChanging();
					this._ComentarioTexto = value;
					this.SendPropertyChanged("ComentarioTexto");
					this.OnComentarioTextoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TablaCargaAlumno_Comentarios", Storage="_TablaCargaAlumno", ThisKey="idComentario", OtherKey="ID", IsForeignKey=true)]
		public TablaCargaAlumno TablaCargaAlumno
		{
			get
			{
				return this._TablaCargaAlumno.Entity;
			}
			set
			{
				TablaCargaAlumno previousValue = this._TablaCargaAlumno.Entity;
				if (((previousValue != value) 
							|| (this._TablaCargaAlumno.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TablaCargaAlumno.Entity = null;
						previousValue.Comentarios = null;
					}
					this._TablaCargaAlumno.Entity = value;
					if ((value != null))
					{
						value.Comentarios = this;
						this._idComentario = value.ID;
					}
					else
					{
						this._idComentario = default(int);
					}
					this.SendPropertyChanged("TablaCargaAlumno");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
